# Generated by Django 5.2.7 on 2025-10-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
