# Generated by Django 5.2.7 on 2025-11-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wangumi_app', '0007_anime_cover_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('COMMENT', '创建了评论'), ('LIKE', '点赞了对象'), ('FOLLOW', '关注了用户'), ('WATCH', '新增追番')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户动态',
                'verbose_name_plural': '用户动态流',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wangumi_app_user_id_9c46e2_idx')],
            },
        ),
    ]
