# Generated by Django 5.2.7 on 2025-11-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0007_anime_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
