# Generated by Django 5.2.7 on 2025-11-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0008_activity'),
        ('wangumi_app', '0008_anime_is_admin'),
    ]

    operations = [
    ]
