# Generated by Django 5.2.7 on 2025-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0009_merge_0008_activity_0008_anime_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy_anime',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('COMMENT', '创建了评论'), ('LIKE', '点赞了对象'), ('WATCH', '新增追番'), ('ITEM', '新建了条目')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
