# Generated by Django 5.2.7 on 2025-11-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0010_add_privacy_anime_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_anime',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_follow',
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followings', models.CharField(default='public', max_length=20)),
                ('followers', models.CharField(default='public', max_length=20)),
                ('watchlist', models.CharField(default='public', max_length=20)),
                ('activities', models.CharField(default='public', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
