# Generated by Django 5.2.7 on 2025-11-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0010_add_privacy_anime_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="is_admin",
            field=models.BooleanField(default=True),
        ),
    ]
