# Generated by Django 5.2.7 on 2025-11-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0011_alter_anime_is_admin"),
        ("wangumi_app", "0011_update_PrivacySetting"),
    ]

    operations = []
