# Generated by Django 5.2.7 on 2025-11-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0013_alter_staffrole_name"),
        ("wangumi_app", "0013_userprofile_gender_userprofile_location_and_more"),
    ]

    operations = []
