# Generated by Django 5.2.7 on 2025-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wangumi_app", "0013_synclog_anime_is_season_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="外部数据源的唯一标识，便于去重同步",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="created_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="synclog",
            name="job_type",
            field=models.CharField(
                choices=[("season", "季度番同步"), ("weekly", "周合集生成")],
                default="weekly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "进行中"),
                    ("success", "成功"),
                    ("failure", "失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="updated_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
