# Generated by Django 5.2.7 on 2025-11-30 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wangumi_app', '0014_merge_20251127_1013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BAN_USER', '封禁用户'), ('UNBAN_USER', '解封用户'), ('DELETE_CONTENT', '删除内容'), ('HANDLE_REPORT', '处理举报')], max_length=20)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管理员操作日志',
                'verbose_name_plural': '管理员操作日志',
                'db_table': 'admin_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN', '封禁用户'), ('UNBAN', '解封用户')], max_length=10)),
                ('reason', models.TextField(verbose_name='操作理由')),
                ('ban_duration', models.IntegerField(blank=True, null=True, verbose_name='封禁天数')),
                ('ban_until', models.DateTimeField(blank=True, null=True, verbose_name='封禁至')),
                ('operated_at', models.DateTimeField(auto_now_add=True)),
                ('operated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ban_operations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户封禁日志',
                'verbose_name_plural': '用户封禁日志',
                'db_table': 'user_ban_logs',
                'ordering': ['-operated_at'],
            },
        ),
    ]
