# Generated by Django 5.2.7 on 2025-11-30 06:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0014_merge_20251127_1013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wangumi_app_search__1b22b4_gin'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='characters_search__4dd01d_gin'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wangumi_app_search__d5a999_gin'),
        ),
        # 添加 PostgreSQL 扩展
        CreateExtension('unaccent'),
        CreateExtension('pg_trgm'),
        # 为 Anime 模型添加触发器
        migrations.RunSQL(
            """
            CREATE TRIGGER anime_search_vector_update
            BEFORE INSERT OR UPDATE OF title, title_cn, description
            ON wangumi_app_anime
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(
                search_vector,
                'pg_catalog.simple',
                title, title_cn, description
            );
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS anime_search_vector_update ON wangumi_app_anime;
            """
        ),
        # 为 Person 模型添加触发器
        migrations.RunSQL(
            """
            CREATE TRIGGER person_search_vector_update
            BEFORE INSERT OR UPDATE OF pers_name, pers_info, summary
            ON wangumi_app_person
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(
                search_vector,
                'pg_catalog.simple',
                pers_name, pers_info, summary
            );
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS person_search_vector_update ON wangumi_app_person;
            """
        ),
        # 为 Character 模型添加触发器
        migrations.RunSQL(
            """
            CREATE TRIGGER character_search_vector_update
            BEFORE INSERT OR UPDATE OF name, summary, infobox
            ON characters
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(
                search_vector,
                'pg_catalog.simple',
                name, summary, infobox
            );
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS character_search_vector_update ON characters;
            """
        ),
        # 为现有数据初始化 search_vector
        migrations.RunSQL(
            """
            UPDATE wangumi_app_anime
            SET search_vector = to_tsvector('pg_catalog.simple',
                COALESCE(title, '') || ' ' || COALESCE(title_cn, '') || ' ' || COALESCE(description, ''));

            UPDATE wangumi_app_person
            SET search_vector = to_tsvector('pg_catalog.simple',
                COALESCE(pers_name, '') || ' ' || COALESCE(pers_info, '') || ' ' || COALESCE(summary, ''));

            UPDATE characters
            SET search_vector = to_tsvector('pg_catalog.simple',
                COALESCE(name, '') || ' ' || COALESCE(summary, '') || ' ' || COALESCE(infobox, ''));
            """
        ),
    ]
