# Generated by Django 5.2.7 on 2025-11-30 07:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0015_anime_search_vector_character_search_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wangumi_app_search__82b3a6_gin'),
        ),
        # 为 UserProfile 模型添加触发器
        migrations.RunSQL(
            """
            CREATE TRIGGER userprofile_search_vector_update
            BEFORE INSERT OR UPDATE OF nickname
            ON wangumi_app_userprofile
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(
                search_vector,
                'pg_catalog.simple',
                nickname
            );
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS userprofile_search_vector_update ON wangumi_app_userprofile;
            """
        ),
        # 为现有数据初始化 search_vector
        migrations.RunSQL(
            """
            UPDATE wangumi_app_userprofile
            SET search_vector = to_tsvector('pg_catalog.simple',
                COALESCE(nickname, '') || ' ' ||
                COALESCE((SELECT username FROM auth_user WHERE id = wangumi_app_userprofile.user_id), ''));
            """
        ),
    ]
