# Generated by Django 5.2.7 on 2025-12-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wangumi_app', '0015_adminlog_userbanlog'),
        ('wangumi_app', '0016_userprofile_search_vector_and_more'),
    ]

    operations = [
    ]
