"""
Django settings for wangumi project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# This resolves to the "backend" directory.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from repo root explicitly so it works when CWD is backend/
# Repo structure: <repo>/.env and <repo>/backend/wangumi/settings.py
load_dotenv(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "wangumi.onrender.com","10.0.2.2","100.80.47.145","123.249.36.248"]
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in [
        f"https://{RENDER_EXTERNAL_HOSTNAME}" if RENDER_EXTERNAL_HOSTNAME else None,
        "https://wangumi.onrender.com",
    ]
    if origin
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "wangumi_app",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "wangumi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "frontend" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wangumi.wsgi.application"

#simple_jwt token settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


#PostgreSQL配置
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "wangumi_db"),
        "USER": os.getenv("DB_USER", "gumi"),
        "PASSWORD": os.getenv("DB_PASSWORD", "1234"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

database_url = os.getenv("DATABASE_URL")
if database_url:
    ssl_required = not database_url.startswith("sqlite")
    DATABASES["default"] = dj_database_url.config(
        conn_max_age=600, ssl_require=ssl_required
    )

    # sqlite 不支持 sslmode，移除不必要的 OPTIONS 配置
    if not ssl_required and "OPTIONS" in DATABASES["default"]:
        DATABASES["default"].pop("OPTIONS", None)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR.parent / "frontend" / "static",
    BASE_DIR.parent / "frontend",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))

CORS_ALLOWED_ORIGINS = [
    origin
    for origin in [
        os.getenv("FRONTEND_URL"),
        "https://wangumi.onrender.com",
        "http://localhost:5173",
    ]
    if origin
]

CORS_ALLOW_CREDENTIALS = True

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
SMS_CODE_TTL_SECONDS = int(os.getenv("SMS_CODE_TTL_SECONDS", "300"))
SMS_DEFAULT_REGION_CODE = os.getenv("SMS_DEFAULT_REGION_CODE", "+86")
SMS_CODE_SECRET = os.getenv("SMS_CODE_SECRET", SECRET_KEY)
VERIFICATION_CODE_REQUEST_INTERVAL_SECONDS = int(os.getenv("VERIFICATION_CODE_REQUEST_INTERVAL_SECONDS", "60"))
VERIFICATION_CODE_DAILY_LIMIT_PER_TARGET = int(os.getenv("VERIFICATION_CODE_DAILY_LIMIT_PER_TARGET", "10"))
VERIFICATION_CODE_DAILY_LIMIT_PER_IP = int(os.getenv("VERIFICATION_CODE_DAILY_LIMIT_PER_IP", "50"))

WEEKLY_COLLECTION_API = os.getenv(
    "WEEKLY_COLLECTION_API",
    "https://example.com/api/weekly-collections",
)
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "2367285113@qq.com")
EMAIL_VERIFICATION_SUBJECT = os.getenv("EMAIL_VERIFICATION_SUBJECT", "Your Wangumi verification code")
EMAIL_HOST=os.getenv("EMAIL_HOST", "smtp.qq.com")
EMAIL_PORT=int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS=os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER=os.getenv("EMAIL_HOST_USER", "2367285113@qq.com")
EMAIL_HOST_PASSWORD=os.getenv("EMAIL_HOST_PASSWORD", "iblkfzhwgfzpdhib")


TENCENT_SMS_SECRET_ID = os.getenv("TENCENT_SMS_SECRET_ID")
TENCENT_SMS_SECRET_KEY = os.getenv("TENCENT_SMS_SECRET_KEY")
TENCENT_SMS_SDK_APP_ID = os.getenv("TENCENT_SMS_SDK_APP_ID")
TENCENT_SMS_SIGN_NAME = os.getenv("TENCENT_SMS_SIGN_NAME")
TENCENT_SMS_TEMPLATE_ID = os.getenv("TENCENT_SMS_TEMPLATE_ID")
TENCENT_SMS_REGION = os.getenv("TENCENT_SMS_REGION", "ap-guangzhou")
TENCENT_SMS_ENDPOINT = os.getenv("TENCENT_SMS_ENDPOINT", "sms.tencentcloudapi.com")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
